// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetCoffee.Infrastructure.Persistence.Context;

#nullable disable

namespace PetCoffee.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240411212040_AddNewTableTransactionProductV4")]
    partial class AddNewTableTransactionProductV4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PetCoffee.Domain.Entities.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Avatar")
                        .HasColumnType("longtext");

                    b.Property<string>("Background")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("EndTimeBlockComment")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("EndTimeBlockPost")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LoginMethod")
                        .HasColumnType("int");

                    b.Property<string>("OTP")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("OTPExpired")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.AccountPromotion", b =>
                {
                    b.Property<long>("PromotionId")
                        .HasColumnType("bigint");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.HasKey("PromotionId", "AccountId");

                    b.HasIndex("AccountId");

                    b.ToTable("AccountPromotion");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.AccountShop", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<long>("ShopId")
                        .HasColumnType("bigint");

                    b.HasKey("AccountId", "ShopId");

                    b.HasIndex("ShopId");

                    b.ToTable("AccountShop");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Area", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<long>("PetcoffeeShopId")
                        .HasColumnType("bigint");

                    b.Property<long>("PricePerHour")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalSeat")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("PetcoffeeShopId");

                    b.ToTable("Area");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<long?>("ParentCommentId")
                        .HasColumnType("bigint");

                    b.Property<long>("PostId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ShopId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("ShopId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<int>("MinParticipants")
                        .HasColumnType("int");

                    b.Property<long>("PetCoffeeShopId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("PetCoffeeShopId");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.EventField", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Answer")
                        .HasColumnType("longtext");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("EventFields");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.FollowPetCfShop", b =>
                {
                    b.Property<long>("ShopId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ShopId", "CreatedById");

                    b.HasIndex("CreatedById");

                    b.ToTable("FollowPetCfShops");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Item", b =>
                {
                    b.Property<long>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Icon")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ItemId");

                    b.HasIndex("CreatedById");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.JoinEvent", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("EventId", "CreatedById");

                    b.HasIndex("CreatedById");

                    b.ToTable("FollowEvents");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Like", b =>
                {
                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<long>("PostId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CreatedById", "PostId");

                    b.HasIndex("PostId");

                    b.ToTable("Like");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Moment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<int>("MomentType")
                        .HasColumnType("int");

                    b.Property<long>("PetId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("PetId");

                    b.ToTable("Diaries");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<string>("Data")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EntityType")
                        .HasColumnType("int");

                    b.Property<bool?>("IsReportForComment")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("longtext");

                    b.Property<long?>("ShopId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CreatedById");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.PackagePromotion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<decimal>("PromotionAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("PromotionDiscount")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("PackagePromotions");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Pet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Avatar")
                        .HasColumnType("longtext");

                    b.Property<string>("Backgound")
                        .HasColumnType("longtext");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("PetCoffeeShopId")
                        .HasColumnType("bigint");

                    b.Property<int>("PetStatus")
                        .HasColumnType("int");

                    b.Property<int>("PetType")
                        .HasColumnType("int");

                    b.Property<bool>("Spayed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TypeSpecies")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("Weight")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("PetCoffeeShopId");

                    b.ToTable("Pet");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.PetArea", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("AreaId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("PetId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("PetId");

                    b.ToTable("PetArea");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.PetCoffeeShop", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("BackgroundUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("ClosedTime")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("EndTimePackage")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FbUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("InstagramUrl")
                        .HasColumnType("longtext");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OpeningTime")
                        .HasColumnType("longtext");

                    b.Property<int>("ParkingType")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("PetCoffeeShop");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Post", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<long?>("ShopId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ShopId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.PostCategory", b =>
                {
                    b.Property<long>("PostId")
                        .HasColumnType("bigint");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PostId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedById");

                    b.ToTable("PostCategories");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.PostPetCoffeeShop", b =>
                {
                    b.Property<long>("PostId")
                        .HasColumnType("bigint");

                    b.Property<long>("ShopId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PostId", "ShopId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ShopId");

                    b.ToTable("PostPetCoffeeShops");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("PetCoffeeShopId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProductStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("PetCoffeeShopId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Promotion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("From")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Percent")
                        .HasColumnType("int");

                    b.Property<long>("PetCoffeeShopId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("To")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("PetCoffeeShopId");

                    b.ToTable("Promotion");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.RatePet", b =>
                {
                    b.Property<long>("PetId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("Rate")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PetId", "CreatedById");

                    b.HasIndex("CreatedById");

                    b.ToTable("RatePet");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Report", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("CommentId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("PostID")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext");

                    b.Property<int>("ReportCategory")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("PostID");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Reservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("AreaId")
                        .HasColumnType("bigint");

                    b.Property<int>("BookingSeat")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsTotallyRefund")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<long?>("PromotionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("Rate")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("PromotionId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.ReservationProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<long>("ReservationId")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalProduct")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReservationId");

                    b.ToTable("ReservationProducts");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.SubmittingEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("EventId");

                    b.ToTable("SubmittingEvent");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.SubmittingEventField", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Answer")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubmittingContent")
                        .HasColumnType("longtext");

                    b.Property<long>("SubmittingEventId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("SubmittingEventId");

                    b.ToTable("SubmittingEventField");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("PackagePromotionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PetCoffeeShopId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PetId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReferenceTransactionId")
                        .HasColumnType("longtext");

                    b.Property<long?>("RemitterId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReservationId")
                        .HasColumnType("bigint");

                    b.Property<int>("TransactionStatus")
                        .HasColumnType("int");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.Property<long>("WalletId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("PackagePromotionId");

                    b.HasIndex("PetCoffeeShopId");

                    b.HasIndex("PetId");

                    b.HasIndex("RemitterId");

                    b.HasIndex("ReservationId");

                    b.HasIndex("WalletId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.TransactionItem", b =>
                {
                    b.Property<long>("TransactionId")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalItem")
                        .HasColumnType("int");

                    b.HasKey("TransactionId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("TransactionItem");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.TransactionProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<long>("TransactionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TransactionId");

                    b.ToTable("transactionProducts");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Vaccination", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ExpireTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("PetId")
                        .HasColumnType("bigint");

                    b.Property<string>("PhotoEvidence")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("VaccinationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("VaccinationType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("Vaccination");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Wallet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Wallet");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.WalletItem", b =>
                {
                    b.Property<long>("WalletId")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalItem")
                        .HasColumnType("int");

                    b.HasKey("WalletId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("WalletItem");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.AccountPromotion", b =>
                {
                    b.HasOne("PetCoffee.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCoffee.Domain.Entities.Promotion", "Promotion")
                        .WithMany("AccountPromotions")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.AccountShop", b =>
                {
                    b.HasOne("PetCoffee.Domain.Entities.Account", "Account")
                        .WithMany("AccountShops")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCoffee.Domain.Entities.PetCoffeeShop", "PetCoffeeShop")
                        .WithMany("AccountShops")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("PetCoffeeShop");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Area", b =>
                {
                    b.HasOne("PetCoffee.Domain.Entities.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("PetCoffee.Domain.Entities.PetCoffeeShop", "PetCoffeeShop")
                        .WithMany("Areas")
                        .HasForeignKey("PetcoffeeShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("PetCoffeeShop");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Category", b =>
                {
                    b.HasOne("PetCoffee.Domain.Entities.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Comment", b =>
                {
                    b.HasOne("PetCoffee.Domain.Entities.Account", "CreatedBy")
                        .WithMany("Comments")
                        .HasForeignKey("CreatedById");

                    b.HasOne("PetCoffee.Domain.Entities.Comment", "ParentComment")
                        .WithMany()
                        .HasForeignKey("ParentCommentId");

                    b.HasOne("PetCoffee.Domain.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCoffee.Domain.Entities.PetCoffeeShop", "PetCoffeeShop")
                        .WithMany("Comments")
                        .HasForeignKey("ShopId");

                    b.Navigation("CreatedBy");

                    b.Navigation("ParentComment");

                    b.Navigation("PetCoffeeShop");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Event", b =>
                {
                    b.HasOne("PetCoffee.Domain.Entities.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("PetCoffee.Domain.Entities.PetCoffeeShop", "PetCoffeeShop")
                        .WithMany("Events")
                        .HasForeignKey("PetCoffeeShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("PetCoffeeShop");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.EventField", b =>
                {
                    b.HasOne("PetCoffee.Domain.Entities.Event", "Event")
                        .WithMany("EventFields")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.FollowPetCfShop", b =>
                {
                    b.HasOne("PetCoffee.Domain.Entities.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCoffee.Domain.Entities.PetCoffeeShop", "Shop")
                        .WithMany("Follows")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Item", b =>
                {
                    b.HasOne("PetCoffee.Domain.Entities.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.JoinEvent", b =>
                {
                    b.HasOne("PetCoffee.Domain.Entities.Account", "CreatedBy")
                        .WithMany("FollowEvents")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCoffee.Domain.Entities.Event", "Event")
                        .WithMany("FollowEvents")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Like", b =>
                {
                    b.HasOne("PetCoffee.Domain.Entities.Account", "CreatedBy")
                        .WithMany("Likes")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCoffee.Domain.Entities.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Moment", b =>
                {
                    b.HasOne("PetCoffee.Domain.Entities.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("PetCoffee.Domain.Entities.Pet", "Pet")
                        .WithMany("Moments")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Notification", b =>
                {
                    b.HasOne("PetCoffee.Domain.Entities.Account", "Account")
                        .WithMany("Notifications")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCoffee.Domain.Entities.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.Navigation("Account");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Pet", b =>
                {
                    b.HasOne("PetCoffee.Domain.Entities.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("PetCoffee.Domain.Entities.PetCoffeeShop", "PetCoffeeShop")
                        .WithMany("Pets")
                        .HasForeignKey("PetCoffeeShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("PetCoffeeShop");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.PetArea", b =>
                {
                    b.HasOne("PetCoffee.Domain.Entities.Area", "Area")
                        .WithMany("PetAreas")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCoffee.Domain.Entities.Pet", "Pet")
                        .WithMany("PetAreas")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.PetCoffeeShop", b =>
                {
                    b.HasOne("PetCoffee.Domain.Entities.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Post", b =>
                {
                    b.HasOne("PetCoffee.Domain.Entities.Account", "CreatedBy")
                        .WithMany("Posts")
                        .HasForeignKey("CreatedById");

                    b.HasOne("PetCoffee.Domain.Entities.PetCoffeeShop", "PetCoffeeShop")
                        .WithMany("Posts")
                        .HasForeignKey("ShopId");

                    b.Navigation("CreatedBy");

                    b.Navigation("PetCoffeeShop");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.PostCategory", b =>
                {
                    b.HasOne("PetCoffee.Domain.Entities.Category", "Category")
                        .WithMany("PostCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCoffee.Domain.Entities.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("PetCoffee.Domain.Entities.Post", "Post")
                        .WithMany("PostCategories")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CreatedBy");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.PostPetCoffeeShop", b =>
                {
                    b.HasOne("PetCoffee.Domain.Entities.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("PetCoffee.Domain.Entities.Post", "Post")
                        .WithMany("PostPetCoffeeShops")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCoffee.Domain.Entities.PetCoffeeShop", "Shop")
                        .WithMany("PostPetCoffeeShops")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Post");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Product", b =>
                {
                    b.HasOne("PetCoffee.Domain.Entities.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("PetCoffee.Domain.Entities.PetCoffeeShop", "PetCoffeeShop")
                        .WithMany("Products")
                        .HasForeignKey("PetCoffeeShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("PetCoffeeShop");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Promotion", b =>
                {
                    b.HasOne("PetCoffee.Domain.Entities.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("PetCoffee.Domain.Entities.PetCoffeeShop", "PetCoffeeShop")
                        .WithMany("Promotions")
                        .HasForeignKey("PetCoffeeShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("PetCoffeeShop");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.RatePet", b =>
                {
                    b.HasOne("PetCoffee.Domain.Entities.Account", "CreatedBy")
                        .WithMany("PetRattings")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCoffee.Domain.Entities.Pet", "Pet")
                        .WithMany("PetRattings")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Report", b =>
                {
                    b.HasOne("PetCoffee.Domain.Entities.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId");

                    b.HasOne("PetCoffee.Domain.Entities.Account", "CreatedBy")
                        .WithMany("Reports")
                        .HasForeignKey("CreatedById");

                    b.HasOne("PetCoffee.Domain.Entities.Post", "Post")
                        .WithMany("Reports")
                        .HasForeignKey("PostID");

                    b.Navigation("Comment");

                    b.Navigation("CreatedBy");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("PetCoffee.Domain.Entities.Area", "Area")
                        .WithMany("Reservations")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCoffee.Domain.Entities.Account", "CreatedBy")
                        .WithMany("Reservations")
                        .HasForeignKey("CreatedById");

                    b.HasOne("PetCoffee.Domain.Entities.Promotion", "Promotion")
                        .WithMany()
                        .HasForeignKey("PromotionId");

                    b.Navigation("Area");

                    b.Navigation("CreatedBy");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.ReservationProduct", b =>
                {
                    b.HasOne("PetCoffee.Domain.Entities.Product", "Product")
                        .WithMany("Invoices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCoffee.Domain.Entities.Reservation", "Reservation")
                        .WithMany("ReservationProducts")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.SubmittingEvent", b =>
                {
                    b.HasOne("PetCoffee.Domain.Entities.Account", "CreatedBy")
                        .WithMany("SubmittingEvents")
                        .HasForeignKey("CreatedById");

                    b.HasOne("PetCoffee.Domain.Entities.Event", "Event")
                        .WithMany("SubmittingEvents")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.SubmittingEventField", b =>
                {
                    b.HasOne("PetCoffee.Domain.Entities.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("PetCoffee.Domain.Entities.SubmittingEvent", "SubmittingEvent")
                        .WithMany("SubmittingEventFields")
                        .HasForeignKey("SubmittingEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("SubmittingEvent");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("PetCoffee.Domain.Entities.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("PetCoffee.Domain.Entities.PackagePromotion", "PackagePromotion")
                        .WithMany("Transactions")
                        .HasForeignKey("PackagePromotionId");

                    b.HasOne("PetCoffee.Domain.Entities.PetCoffeeShop", "PetCoffeeShop")
                        .WithMany("Transactions")
                        .HasForeignKey("PetCoffeeShopId");

                    b.HasOne("PetCoffee.Domain.Entities.Pet", "Pet")
                        .WithMany("Transactions")
                        .HasForeignKey("PetId");

                    b.HasOne("PetCoffee.Domain.Entities.Wallet", "Remitter")
                        .WithMany()
                        .HasForeignKey("RemitterId");

                    b.HasOne("PetCoffee.Domain.Entities.Reservation", "Reservation")
                        .WithMany("Transactions")
                        .HasForeignKey("ReservationId");

                    b.HasOne("PetCoffee.Domain.Entities.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("PackagePromotion");

                    b.Navigation("Pet");

                    b.Navigation("PetCoffeeShop");

                    b.Navigation("Remitter");

                    b.Navigation("Reservation");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.TransactionItem", b =>
                {
                    b.HasOne("PetCoffee.Domain.Entities.Item", "Item")
                        .WithMany("Transactions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCoffee.Domain.Entities.Transaction", "Transaction")
                        .WithMany("Items")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.TransactionProduct", b =>
                {
                    b.HasOne("PetCoffee.Domain.Entities.Product", "Product")
                        .WithMany("TransactionProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCoffee.Domain.Entities.Transaction", "Transaction")
                        .WithMany("TransactionProducts")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Vaccination", b =>
                {
                    b.HasOne("PetCoffee.Domain.Entities.Pet", "Pet")
                        .WithMany("Vaccinations")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Wallet", b =>
                {
                    b.HasOne("PetCoffee.Domain.Entities.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.WalletItem", b =>
                {
                    b.HasOne("PetCoffee.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCoffee.Domain.Entities.Wallet", "Wallet")
                        .WithMany("Items")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Account", b =>
                {
                    b.Navigation("AccountShops");

                    b.Navigation("Comments");

                    b.Navigation("FollowEvents");

                    b.Navigation("Likes");

                    b.Navigation("Notifications");

                    b.Navigation("PetRattings");

                    b.Navigation("Posts");

                    b.Navigation("Reports");

                    b.Navigation("Reservations");

                    b.Navigation("SubmittingEvents");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Area", b =>
                {
                    b.Navigation("PetAreas");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Category", b =>
                {
                    b.Navigation("PostCategories");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Event", b =>
                {
                    b.Navigation("EventFields");

                    b.Navigation("FollowEvents");

                    b.Navigation("SubmittingEvents");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Item", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.PackagePromotion", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Pet", b =>
                {
                    b.Navigation("Moments");

                    b.Navigation("PetAreas");

                    b.Navigation("PetRattings");

                    b.Navigation("Transactions");

                    b.Navigation("Vaccinations");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.PetCoffeeShop", b =>
                {
                    b.Navigation("AccountShops");

                    b.Navigation("Areas");

                    b.Navigation("Comments");

                    b.Navigation("Events");

                    b.Navigation("Follows");

                    b.Navigation("Pets");

                    b.Navigation("PostPetCoffeeShops");

                    b.Navigation("Posts");

                    b.Navigation("Products");

                    b.Navigation("Promotions");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");

                    b.Navigation("PostCategories");

                    b.Navigation("PostPetCoffeeShops");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Product", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("TransactionProducts");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Promotion", b =>
                {
                    b.Navigation("AccountPromotions");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Reservation", b =>
                {
                    b.Navigation("ReservationProducts");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.SubmittingEvent", b =>
                {
                    b.Navigation("SubmittingEventFields");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Transaction", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("TransactionProducts");
                });

            modelBuilder.Entity("PetCoffee.Domain.Entities.Wallet", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
