
namespace PetCoffee.Application.Common.Constantsl;

public class EmailConstant
{
	public static string EmailSubject = "Mã Xác Minh Của Bạn";
	public static string EmailSubjectShopRequest= "Yêu cầu tạo cửa hàng";
	public static string InactiveEmailSubject = "Tài khoản của bạn đã bị vô hiệu hóa";
	public static string EmailForm = " <h1>Chào bạn {0},</h1>\r\n\r\n  <p>Cảm ơn bạn đã chọn dịch vụ của chúng tôi! Để hoàn tất quá trình đăng ký và tăng cường bảo mật cho tài khoản của bạn, chúng tôi yêu cầu bạn xác minh địa chỉ email.</p>\r\n\r\n  <p>Mã xác minh của bạn là: <strong>{1}</strong></p>\r\n\r\n  <p>Vui lòng nhập mã này trên trang web của chúng tôi để hoàn tất quá trình xác minh. Nếu bạn không yêu cầu mã này hoặc có bất kỳ lo ngại nào, vui lòng liên hệ ngay với đội hỗ trợ của chúng tôi.</p>\r\n\r\n  <p>Cảm ơn bạn đã hợp tác.</p>\r\n\r\n  <p>Trân trọng,</p>\r\n\r\n  <p>Pet Coffee Platform</p>";
	public static string EmailOTPForm = " <p>Chào bạn {0},</p>\r\n\r\n  <p>Mã xác minh để đổi mật khẩu của bạn là:</p>\r\n\r\n  <h1 style=\"font-size: 24px; font-weight: bold;\">{1}</h1>\r\n\r\n  <p>Vui lòng nhập mã này vào trang web của chúng tôi để hoàn tất quá trình đổi mật khẩu</p>\r\n\r\n  <p>Nếu bạn không yêu cầu đổi mật khẩu hoặc gặp bất kỳ vấn đề nào, vui lòng liên hệ với bộ phận hỗ trợ của chúng tôi.</p>\r\n\r\n  <p>Cảm ơn bạn đã sử dụng dịch vụ của chúng tôi.</p>\r\n\r\n  <p>Trân trọng,</p>";
	public static string AcceptShop = "<p>Chào bạn {0},</p>\r\n\r\n  <p>Tin vui! Quán cà phê của bạn đã được kích hoạt thành công trên ứng dụng của chúng tôi.</p>\r\n\r\n  <p>Bây giờ bạn có thể:</p>\r\n\r\n  <ul>\r\n    <li>Quản lý thông tin quán cà phê của bạn</li>\r\n    <li>Nhận đơn đặt hàng trực tuyến</li>\r\n    <li>Tương tác với khách hàng</li>\r\n    <li>Và nhiều hơn nữa!</p>\r\n  </ul>\r\n\r\n  <p>Hãy truy cập ứng dụng của chúng tôi để bắt đầu trải nghiệm:</p>";
	public static string RejectShop = "<p>Chào bạn {0},</p>\r\n\r\n  <p>Chúng tôi rất tiếc phải thông báo rằng yêu cầu tạo quán cà phê của bạn trên ứng dụng của chúng tôi đã bị từ chối.</p>\r\n\r\n  <p>Lý do từ chối:</p>\r\n\r\n  <p>{1}</p>\r\n\r\n  <p>Vui lòng xem xét lại yêu cầu của bạn và đảm bảo rằng bạn đã cung cấp đầy đủ thông tin cần thiết và tuân thủ các quy định của chúng tôi.</p><p>Đội ngũ hỗ trợ của chúng tôi luôn sẵn sàng hỗ trợ bạn. Vui lòng liên hệ với chúng tôi nếu bạn có bất kỳ thắc mắc nào.</p>\r\n\r\n  <p>Cảm ơn bạn đã sử dụng dịch vụ của chúng tôi!</p>\r\n\r\n  <p>Trân trọng,</p>";
	public static string InActiveShop = "<p>Chào bạn {0},</p>\r\n\r\n  <p>Chúng tôi rất tiếc phải thông báo rằng quán cà phê của bạn trên ứng dụng của chúng tôi đã bị vô hiệu hóa.</p>\r\n\r\n  <p>Lý do vô hiệu hóa:</p>\r\n\r\n  <p>{1}</p>\r\n\r\n  <p>Vui lòng liên hệ với bộ phận hỗ trợ của chúng tôi nếu bạn có bất kỳ thắc mắc nào về việc vô hiệu hóa này.</p> <p>Cảm ơn bạn đã sử dụng dịch vụ của chúng tôi!</p>\r\n\r\n  <p>Trân trọng,</p>\r\n";
	public static string InactiveCustomerAccount = "<p>Chào bạn,</p>\r\n\r\n  <p>Chúng tôi rất tiếc phải thông báo rằng tài khoản của bạn đã bị vô hiệu hóa.</p>\r\n\r\n<p>Nếu bạn tin rằng tài khoản của bạn bị vô hiệu hóa nhầm lẫn, vui lòng liên hệ với bộ phận hỗ trợ của chúng tôi để được xem xét.</p>";
}
